version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: npm run devStart
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=3000
      - API_BASE_URL=https://www.pegelonline.wsv.de/webservices/rest-api/v2
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: npm run devStart
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    environment:
      - PORT=80
      - API_URL=http://backend:3000
      - NODE_ENV=development
