version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - PORT=80
      - API_URL=http://backend:3000
