version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: npm run devStart
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=3000

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: npm run devStart
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    environment:
      - PORT=80
      - API_URL=http://backend:3000
