apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend-image
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: 80
        - name: API_URL
          value: http://backend-service:3000
        - name: NODE_ENV
          value: production
          